FROM mcr.microsoft.com/dotnet/sdk:9.0 AS dev

WORKDIR /app

COPY ./Virtuelly.sln ./
COPY ./src ./src

RUN dotnet restore ./src/Services/IdentityService/IdentityService.csproj

CMD ["dotnet", "watch", "run", "--project", "src/Services/IdentityService/IdentityService.csproj", "--no-hot-reload"]
