--CREATE USER dev WITH PASSWORD 'dev@123456';

--GRANT CONNECT ON DATABASE virtuelly TO dev;

--GRANT USAGE ON SCHEMA public TO dev; -- Grant usage on the default public schema

--For existing schemas, you can construct a loop
-- DO $$
-- DECLARE
--     sch text;
-- BEGIN
--     FOR sch IN SELECT nspname FROM pg_namespace LOOP
--         EXECUTE format('GRANT USAGE ON SCHEMA %I TO dev', sch);
--     END LOOP;
-- END;
-- $$;

--SELECT schema_name FROM information_schema.schemata;

--     GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dev;
--     GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO dev;
--     GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO dev;

--     -- Repeat for other schemas if necessary, or use the following for all existing objects in all schemas:

-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "admin" TO dev;
--   GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA  "admin" TO dev;
--       GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA  "admin" TO dev;

-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "jobs" TO dev;
--   GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA  "jobs" TO dev;
--     GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA  "jobs" TO dev;
  
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "geo" TO dev;
--   GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA  "geo" TO dev;
--     GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA  "geo" TO dev;
  
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "support" TO dev;
--   GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA  "support" TO dev;
--     GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA  "support" TO dev;
  
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "events" TO dev;
--   GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "events" TO dev;
--     GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "events" TO dev;
  
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "payments" TO dev;
--   GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA  "payments" TO dev;
--     GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA  "payments" TO dev;
  
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "notifications" TO dev;
--   GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "notifications" TO dev;
--     GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "notifications" TO dev;
  
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "marketing" TO dev;
--   GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA  "marketing" TO dev;
--     GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA  "marketing" TO dev;
  
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "booking" TO dev;
--   GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA  "booking" TO dev;
--     GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA  "booking" TO dev;
  
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "catalog" TO dev;
--   GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA  "catalog" TO dev;
--     GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA  "catalog" TO dev;
  
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "profiles" TO dev;
--   GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA  "profiles" TO dev;
--     GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA  "profiles" TO dev;
  
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "identity" TO dev;
--   GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA  "identity" TO dev;
--     GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA  "identity" TO dev;


-- Grant permissions on all tables that will be created in the future
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO dev;


-- ALTER DEFAULT PRIVILEGES IN SCHEMA admin GRANT ALL PRIVILEGES ON  TABLES  		TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA admin GRANT ALL PRIVILEGES ON  SEQUENCES 	TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA admin GRANT ALL PRIVILEGES ON  FUNCTIONS 	TO dev;

-- ALTER DEFAULT PRIVILEGES IN SCHEMA "jobs" GRANT ALL PRIVILEGES ON  TABLES  		TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "jobs" GRANT ALL PRIVILEGES ON  SEQUENCES 	TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "jobs" GRANT ALL PRIVILEGES ON  FUNCTIONS 	TO dev;
  
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "geo"  GRANT ALL PRIVILEGES ON  TABLES  		TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "geo"  GRANT ALL PRIVILEGES ON  SEQUENCES 	TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "geo"  GRANT ALL PRIVILEGES ON  FUNCTIONS  	TO dev;
  
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "support"GRANT ALL PRIVILEGES ON  TABLES  	TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "support"GRANT ALL PRIVILEGES ON  SEQUENCES 	TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "support"GRANT ALL PRIVILEGES ON  FUNCTIONS 	TO dev;
  
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "events" GRANT ALL PRIVILEGES ON  TABLES 	TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "events" GRANT ALL PRIVILEGES ON  SEQUENCES 	TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "events" GRANT ALL PRIVILEGES ON  FUNCTIONS 	TO dev;
  
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "payments" GRANT ALL PRIVILEGES ON  TABLES 		TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "payments" GRANT ALL PRIVILEGES ON  SEQUENCES  	TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "payments" GRANT ALL PRIVILEGES ON  FUNCTIONS 	TO dev;

-- ALTER DEFAULT PRIVILEGES IN SCHEMA "notifications" 	GRANT ALL PRIVILEGES ON  TABLES  	TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "notifications"  GRANT ALL PRIVILEGES ON  SEQUENCES  TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "notifications" 	GRANT ALL PRIVILEGES ON  FUNCTIONS  TO dev;

-- ALTER DEFAULT PRIVILEGES IN SCHEMA "marketing" GRANT ALL PRIVILEGES ON  TABLES 		TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "marketing" GRANT ALL PRIVILEGES ON  SEQUENCES 	TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "marketing" GRANT ALL PRIVILEGES ON  FUNCTIONS  	TO dev;

-- ALTER DEFAULT PRIVILEGES IN SCHEMA "booking" GRANT ALL PRIVILEGES ON  TABLES 		TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "booking" GRANT ALL PRIVILEGES ON  SEQUENCES 	TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "booking" GRANT ALL PRIVILEGES ON  FUNCTIONS 	TO dev;

-- ALTER DEFAULT PRIVILEGES IN SCHEMA "catalog" GRANT ALL PRIVILEGES ON  TABLES 		TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "catalog" GRANT ALL PRIVILEGES ON  SEQUENCES 	TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "catalog" GRANT ALL PRIVILEGES ON  FUNCTIONS 	TO dev;

-- ALTER DEFAULT PRIVILEGES IN SCHEMA "profiles" GRANT ALL PRIVILEGES ON  TABLES 		TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "profiles" GRANT ALL PRIVILEGES ON  SEQUENCES 	TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "profiles" GRANT ALL PRIVILEGES ON  FUNCTIONS  	TO dev;

-- ALTER DEFAULT PRIVILEGES IN SCHEMA "identity" GRANT ALL PRIVILEGES ON  TABLES 		TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "identity" GRANT ALL PRIVILEGES ON  SEQUENCES  	TO dev;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "identity" GRANT ALL PRIVILEGES ON  FUNCTIONS  	TO dev;










  